package:
  name: distutils-activate-mingw
  version: 2.3

build:
  number: 6
  skip: true  # [not win]
  python_version_independent: true

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python_min }}.*
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - gcc_{{ target_platform }}
  files:
    - spam.c

outputs:
  - name: distutils-activate-mingw

  - name: libpython
    requirements:
      - distutils-activate-mingw

about:
  home: https://github.com/conda-forge/libpython-feedstock
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A mingw-w64 import library for python??.dll (on Windows)

extra:
  feedstock-name: libpython
  recipe-maintainers:
    - chrisburr
    - isuruf
